Submission
Significa/frontend-challenge pull request #6
Opened 2018-10-25 17:32 UTC by isabelsoasa

Unfinished submission, missing loads.

2018-10-29 10:19 UTC, pbrandone commented on my-code/src/components/Button/index.js
> +    <Heart />
Why does Button have a Heart?

2018-10-29 10:19 UTC, pbrandone commented on my-code/src/components/Button/styled.js
> +type ThemeType = {
this can be moved to its own file, If is used more than once

2018-10-29 10:19 UTC, pbrandone commented on my-code/src/components/Button/styled.js
> +  background-color: ${(p: PropType) =>
yeah, I have to admit that flow here feels a bit strange, I think we're ok if we don't flow type the styled files

2018-10-29 10:19 UTC, pbrandone commented on my-code/src/components/IconButton/index.js
> +// @flow
I guess this wasn't used

2018-10-29 10:19 UTC, pbrandone commented on my-code/src/constants/omdbApi.js
> +  API_KEY: "a4e8e9b2",
careful with adding API keys to the repo.
take a look at [dotenv](https://www.npmjs.com/package/dotenv)

2018-10-29 10:19 UTC, pbrandone commented on my-code/src/containers/App.js
> +  <BrowserRouter>
Maybe a 404?

2018-10-29 10:19 UTC, pbrandone commented on my-code/src/containers/Detail.js
> +class Detail extends React.Component<PropsType, StateType> {
What if the ID doesn't return a movie?

2018-10-29 10:19 UTC, pbrandone commented on my-code/src/containers/Detail.js
> +      favourite: false,
shouldn't we check if it's favorite before setting it to false?

2018-10-29 10:19 UTC, pbrandone commented on my-code/src/containers/Detail.js
> +      active: false
what's the active?
Can't we just use favorite?

That being sad, do we need the favorite key in the state or could we just use localstorage as the source-of-truth for favorites?

2018-10-29 10:19 UTC, pbrandone commented on my-code/src/containers/Detail.js
> +          ) : null}
If it's a conditional render no need to use ternaries and return null. you could just `info.Ratings &&`

2018-10-29 10:37 UTC, danilowoz requested changes

2018-10-29 10:37 UTC, danilowoz commented on my-code/src/components/Button/index.js
> +const Button = ({ text, ...props }: PropsType) => (
Did you use `onChange`? If so, please create a type for it

2018-10-29 10:37 UTC, danilowoz commented on my-code/src/components/Results.js
> +const Results = (props: PropsType) => {
Quick tip:
```jsx
const Results = ({ data }: PropsType) => {
```

Then you can remove the next line

2018-10-29 10:37 UTC, danilowoz commented on my-code/src/components/Thumbnail/styled.js
> +const SmallEmptyThumbnail = styled.div`
You can export directly the const here, instead of at the end of the file:

`export const SmallEmptyThumbnail = styled.div` `

2018-10-29 10:37 UTC, danilowoz commented on my-code/src/containers/Detail.js
> +    console.log(info)
Avoid leaving the consoles, is there any warning in the eslint?

2018-11-05 13:50 UTC, danilowoz commented
Thanks @isabelsoasa 🎉

2018-11-05 13:50 UTC, closed without merging